{% set name = "tuna" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ff8b426be4bc389f35e4d23feedd886ddd9ff7e4579704beff492b304287533

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tuna = tuna.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    # While not strictly necessary for python 3.8 and above
    # it does make the package noarch if we simply include it without
    # a selector
    - importlib_metadata

test:
  commands:
    - tuna --help

about:
  home: https://github.com/nschloe/tuna
  license: MIT
  license_family: MIT
  # no license file included in source
  # https://github.com/nschloe/tuna/issues/36
  license_file: LICENSE
  summary: tuna is a Python profile viewer inspired by the amazing SnakeViz.

extra:
  recipe-maintainers:
    - hmaarrfk
