{% set name = "tuna" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a487b13fa564101bbc71b731689e1f86b599789c3d940f4b2f40580eefd2133e

build:
  number: 0
  # Importlib is not python3.8 safe
  # noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tuna = tuna.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - importlib_metadata  # [py<38]

test:
  commands:
    - tuna --help

about:
  home: https://github.com/nschloe/tuna
  license: MIT
  license_family: MIT
  # no license file included in source
  # https://github.com/nschloe/tuna/issues/36
  license_file: LICENSE
  summary: tuna is a Python profile viewer inspired by the amazing SnakeViz.

extra:
  recipe-maintainers:
    - hmaarrfk
