{% set name = "tuna" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27896850d32678be7d1f2e15fea2b2ea8f74852396fdd8358374a14349c1791d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - tuna = tuna.cli:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  commands:
    - tuna --help

about:
  home: https://github.com/nschloe/tuna
  license: MIT
  license_family: MIT
  # no license file included in source
  # https://github.com/nschloe/tuna/issues/36
  license_file: LICENSE
  summary: 'tuna is a Python profile viewer inspired by the amazing SnakeViz.'

extra:
  recipe-maintainers:
    - hmaarrfk
