travis:
  secure:
    BINSTAR_TOKEN: jJAREAxrOAzshWIHpZ4rvo7son0Ant/5Ye7SPmmrwSYeZrrl5ty0wGJub6szS9fi/wJzdXmxAuu3hr0+ab6a+18gNsBXTWxIAXw6kuNL2lyBc/zYqjJ/fTrhooHDzheTB4C5VnKipY8rYcu/iNno7SKFov+7pp8AJxo4tfvYAWDTYPFHP7tpQUWCAZaMrqrvMZY3+q30dPS/jWzqn4japIopBplwTfJqnXdjKtZgnZcApJJun4mtin4o6Ys3cyU0czRCLgbS5TJaIl49wIz9Uyv/yawEEswePcrromxWo093gUoY1+PJhR34zWXhcn+vdMT6Oll2T+3K3kOE2i8xuIAWjg1axnxBCrB9Zifwhx3l92sZe/qlB+dElfTII+x+5i06iOLihAfMbzCYYApWLAiTAsFwGpoGxsC3UEfQ4NlYlYSsgX3miO1bLSs1tcRHC6k7EoBpE3koIxokKpztg7QwidXrd1JgThQVADBygfWi2A1GMgm8w7QE6fvXb9AQxUYhYqsQhun10EEUE9XQTn0gMDFjg0i6NN6KaZworm9j8ZF/yY9taNTfwbHRbuZnky7SH502m5UL1a8D77yMF48ASa+A5izmN640uzqlJxkkWhW+ry+0/cfubpf7Tzy86VH/DuktrL0hZ8PJLaO1JzuWjqb4XABG93vLU5V5qcU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
